# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie > 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/foundation-sites/scss"
    - "bower_components/motion-ui/src"

  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    # Libraries required by Foundation
    - "bower_components/what-input/what-input.js"
    # Core Foundation files
    - "bower_components/foundation-sites/js/foundation.core.js"
    - "bower_components/foundation-sites/js/foundation.util.*.js"
    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    - "bower_components/foundation-sites/js/foundation.abide.js"
    #- "bower_components/foundation-sites/js/foundation.accordion.js"
    #- "bower_components/foundation-sites/js/foundation.accordionMenu.js"
    - "bower_components/foundation-sites/js/foundation.drilldown.js"
    - "bower_components/foundation-sites/js/foundation.dropdown.js"
    - "bower_components/foundation-sites/js/foundation.dropdownMenu.js"
    #- "bower_components/foundation-sites/js/foundation.equalizer.js"
    #- "bower_components/foundation-sites/js/foundation.interchange.js"
    #- "bower_components/foundation-sites/js/foundation.magellan.js"
    #- "bower_components/foundation-sites/js/foundation.offcanvas.js"
    - "bower_components/foundation-sites/js/foundation.orbit.js"
    - "bower_components/foundation-sites/js/foundation.responsiveMenu.js"
    - "bower_components/foundation-sites/js/foundation.responsiveToggle.js"
    - "bower_components/foundation-sites/js/foundation.reveal.js"
    #- "bower_components/foundation-sites/js/foundation.slider.js"
    - "bower_components/foundation-sites/js/foundation.sticky.js"
    - "bower_components/foundation-sites/js/foundation.tabs.js"
    - "bower_components/foundation-sites/js/foundation.toggler.js"
    #- "bower_components/foundation-sites/js/foundation.tooltip.js"

    # Paths to template code
    - "min/js/dev-tools.js" # this should load before Foundation, to set up the nav
    - "min/js/app.js"
    - "min/js/!(app).js" # if it's not Foundation, load it afterward

  # Path to independent scripts that we don't want to combine together
  # They'll load in /js/ as .min.js files
  singles:
    - "min/scripts/**/*"

  # Images
  images:
    - "min/img/**/*"